import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Alex Rossignol Developpement",
  description: "Generated by create next app",
};

export const dmBold = localFont({
  src: "../../public/fonts/DMSans-Bold.ttf",
  variable: "--font-title-bold",
  display: "swap",
});
export const rubikRegular = localFont({
  src: "../../public/fonts/Rubik-Regular.ttf",
  variable: "--font-text-regular",
  display: "swap",
});
export const rubikMedium = localFont({
  src: "../../public/fonts/Rubik-Medium.ttf",
  variable: "--font-text-medium",
  display: "swap",
});
export const rubikBold = localFont({
  src: "../../public/fonts/Rubik-Bold.ttf",
  variable: "--font-text-bold",
  display: "swap",
});
export const rubikLight = localFont({
  src: "../../public/fonts/Rubik-Light.ttf",
  variable: "--font-text-light",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className={`
    ${rubikRegular.variable} 
    ${rubikMedium.variable}  
    ${rubikBold.variable} 
    ${rubikLight.variable} 
    ${dmBold.variable} 
  `}
    >
      <body>{children}</body>
    </html>
  );
}
