import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/colors.css";
import "@/styles/size.css";
import "@/styles/fonts.css";

export const metadata: Metadata = {
  title: "Alex Rossignol Developpement",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>{children}</body>
    </html>
  );
}
